name: Shahar Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Generate Slideshows
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:3.0.1
      volumes:
        - ${{ github.workspace }}:/app

    steps:
    - name: Checkout The Repo
      uses: actions/checkout@v2
    - name: Install make
      run: apk add make
    - name: Build
      run: make
    - name: Upload Output
      uses: actions/upload-artifact@v2
      with:
        name: slideshows
        path: dist
